[package]
name = "ice-repro"
version = "0.1.0"
authors = ["RobbieClarken <robbie.clarken@gmail.com>"]
edition = "2018"

[dependencies]
macros = { path = "macros" }

[workspace]
members = ["macros", "macros-impl"]
