[package]
name = "macros"
version = "0.1.0"
authors = ["RobbieClarken <robbie.clarken@gmail.com>"]
edition = "2018"

[dependencies]
macros-impl = { path = "../macros-impl" }
proc-macro-hack = "0.5.11"
